### PR TITLE
Fix an issue with a last column being empty :/

### PR DESCRIPTION
**Pull request by stem**
Hi,

After some random user files, I've encountered an issue with a perfectly valid CSV (meaning that it has an header line + some content lines, each with the same amount of comma), but some content lines have an empty last column, and it wasn't parsed that way : I had 30 columns for the headers, and only 29 columns for some content.

You can find the tests that I can think of, and a "fix" that I don't really understand why it works, but it didn't break anything 😇 

Let me know if you see anything that could be improved.

Thanks for your work.

### CODE REVIEW

**Comment by SebastienElet** [comment]
Hello @stem, thanks a lot for your contribution.
I can not do any better 👍 .

I'm going to merge this and publish the patch on npm.

**Comment by SebastienElet** [comment]
@stem the `1.0.2` is available on npm.

Considering the quality of your work, we added you as collaborator on this repository.

**Comment by stem** [comment]
Good news :)

Thanks for the collaborator thing on this repo. Let me know if you have some "rules" to apply before merging.

**Comment by SebastienElet** [comment]
The rules are : common sens, tests, lint & humility 😉  (Like this PR)

**Pull request merged**
